export const cityData = {
    bangalore: [
      {
        id: 1,
        name: 'The Veggie Delight',
        streetAddress: '123 Green Street',
        city: 'Bangalore',
        state: 'Karnataka',
        contact: '9876543210',
        workingDays: 'Monday to Saturday',
        mealTimings: 'Breakfast, Lunch, Dinner',
        mealType: 'Veg',
        charges: '₹2000',
        images: ['img1.jpg', 'img2.jpg'],
        terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
      },
      {
        id: 2,
        name: 'Spicy Bites',
        streetAddress: '456 Spice Lane',
        city: 'Bangalore',
        state: 'Karnataka',
        contact: '9123456789',
        workingDays: 'Tuesday to Sunday',
        mealTimings: 'Lunch, Dinner',
        mealType: 'Both (Veg & Non-Veg)',
        charges: '₹2500',
        images: ['img3.jpg', 'img4.jpg'],
        terms_condition: 'Orders can be customized. No refunds after meal delivery.'
      },
      {
        id: 3,
        name: 'Healthy Eats',
        streetAddress: '789 Wellness Avenue',
        city: 'Bangalore',
        state: 'Karnataka',
        contact: '9654321098',
        workingDays: 'Monday to Friday',
        mealTimings: 'Breakfast, Lunch, Dinner',
        mealType: 'Veg',
        charges: '₹1800',
        images: ['img5.jpg', 'img6.jpg'],
        terms_condition: 'Discounts available for weekly orders. No cancellations after 6 PM.'
      },
    ],
    delhi: [
      {
        id: 1,
        name: 'Delhi Delights',
        streetAddress: '101 Mughal Road',
        city: 'Delhi',
        state: 'Delhi',
        contact: '9988776655',
        workingDays: 'Monday to Sunday',
        mealTimings: 'Breakfast, Lunch, Dinner',
        mealType: 'Both (Veg & Non-Veg)',
        charges: '₹2200',
        images: ['img7.jpg', 'img8.jpg'],
        terms_condition: 'Meals can be adjusted as per taste. 50% refund for cancellations 2 hours before delivery.'
      },
      {
        id: 2,
        name: 'Tasty Treats',
        streetAddress: '202 Flavor Street',
        city: 'Delhi',
        state: 'Delhi',
        contact: '9777888999',
        workingDays: 'Wednesday to Monday',
        mealTimings: 'Breakfast, Lunch, Dinner',
        mealType: 'Veg',
        charges: '₹2100',
        images: ['img9.jpg', 'img10.jpg'],
        terms_condition: 'No refunds for missed orders. Minimum order of 3 meals required.'
      },
      {
        id: 3,
        name: 'North Indian Flavors',
        streetAddress: '303 Spice Market',
        city: 'Delhi',
        state: 'Delhi',
        contact: '9666554433',
        workingDays: 'Monday to Saturday',
        mealTimings: 'Breakfast, Lunch, Dinner',
        mealType: 'Both (Veg & Non-Veg)',
        charges: '₹2300',
        images: ['img11.jpg', 'img12.jpg'],
        terms_condition: 'Special discounts for bulk orders. No cancellations after 12 PM.'
      },
    ],

    mumbai: [
        {
          id: 1,
          name: 'Mumbai Munchies',
          streetAddress: '10 Marine Drive',
          city: 'Mumbai',
          state: 'Maharashtra',
          contact: '9123456780',
          workingDays: 'Monday to Sunday',
          mealTimings: 'Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹3000',
          images: ['img21.jpg', 'img22.jpg'],
          terms_condition: 'Cancellations allowed up to 3 hours before delivery. No refunds after delivery.'
        },
        {
          id: 2,
          name: 'Spice Route',
          streetAddress: '22 Colaba Causeway',
          city: 'Mumbai',
          state: 'Maharashtra',
          contact: '9234567891',
          workingDays: 'Monday to Friday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2800',
          images: ['img23.jpg', 'img24.jpg'],
          terms_condition: 'Discounts for monthly subscriptions. No cancellations after 8 PM.'
        },
        {
          id: 3,
          name: 'The Healthy Plate',
          streetAddress: '45 Bandra West',
          city: 'Mumbai',
          state: 'Maharashtra',
          contact: '9345678902',
          workingDays: 'Tuesday to Sunday',
          mealTimings: 'Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2500',
          images: ['img25.jpg', 'img26.jpg'],
          terms_condition: 'Orders can be customized. No refunds after meal delivery.'
        },
        {
          id: 4,
          name: 'Gourmet Delights',
          streetAddress: '78 Andheri East',
          city: 'Mumbai',
          state: 'Maharashtra',
          contact: '9456789012',
          workingDays: 'Monday to Saturday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2700',
          images: ['img27.jpg', 'img28.jpg'],
          terms_condition: 'Special discounts for bulk orders. No cancellations after 9 PM.'
        },
        {
          id: 5,
          name: 'Mumbai Tiffins',
          streetAddress: '101 Dadar West',
          city: 'Mumbai',
          state: 'Maharashtra',
          contact: '9567890123',
          workingDays: 'Wednesday to Monday',
          mealTimings: 'Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2600',
          images: ['img29.jpg', 'img30.jpg'],
          terms_condition: 'No refunds for missed orders. Minimum order of 3 meals required.'
        }
      ],
      jaipur: [
        {
          id: 1,
          name: 'Jaipur Tiffins',
          streetAddress: '123 Pink City Road',
          city: 'Jaipur',
          state: 'Rajasthan',
          contact: '9876543211',
          workingDays: 'Monday to Saturday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2200',
          images: ['img31.jpg', 'img32.jpg'],
          terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
        },
        {
          id: 2,
          name: 'Royal Flavors',
          streetAddress: '456 Amber Fort',
          city: 'Jaipur',
          state: 'Rajasthan',
          contact: '9123456782',
          workingDays: 'Tuesday to Sunday',
          mealTimings: 'Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2400',
          images: ['img33.jpg', 'img34.jpg'],
          terms_condition: 'Orders can be customized. No refunds after meal delivery.'
        },
        {
          id: 3,
          name: 'Pink City Bites',
          streetAddress: '789 Hawa Mahal',
          city: 'Jaipur',
          state: 'Rajasthan',
          contact: '9654321093',
          workingDays: 'Monday to Friday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2100',
          images: ['img35.jpg', 'img36.jpg'],
          terms_condition: 'Discounts available for weekly orders. No cancellations after 6 PM.'
        },
        {
          id: 4,
          name: 'Rajasthani Delights',
          streetAddress: '101 Jantar Mantar',
          city: 'Jaipur',
          state: 'Rajasthan',
          contact: '9988776655',
          workingDays: 'Monday to Sunday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2300',
          images: ['img37.jpg', 'img38.jpg'],
          terms_condition: 'Meals can be adjusted as per taste. 50% refund for cancellations 2 hours before delivery.'
        },
        {
          id: 5,
          name: 'Tasty Treats',
          streetAddress: '202 Flavor Street',
          city: 'Jaipur',
          state: 'Rajasthan',
          contact: '9777888999',
          workingDays: 'Wednesday to Monday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2000',
          images: ['img39.jpg', 'img40.jpg'],
          terms_condition: 'No refunds for missed orders. Minimum order of 3 meals required.'
        }
      ],
      hyderabad: [
        {
          id: 1,
          name: 'Hyderabad Biryani House',
          streetAddress: '123 Charminar Road',
          city: 'Hyderabad',
          state: 'Telangana',
          contact: '9876543212',
          workingDays: 'Monday to Saturday',
          mealTimings: 'Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2500',
          images: ['img41.jpg', 'img42.jpg'],
          terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
        },
        {
          id: 2,
          name: 'Nawabi Tastes',
          streetAddress: '456 Golconda Fort',
          city: 'Hyderabad',
          state: 'Telangana',
          contact: '9123456783',
          workingDays: 'Tuesday to Sunday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2300',
          images: ['img43.jpg', 'img44.jpg'],
          terms_condition: 'Orders can be customized. No refunds after meal delivery.'
        },
        {
          id: 3,
          name: 'Healthy Eats',
          streetAddress: '789 HITEC City',
          city: 'Hyderabad',
          state: 'Telangana',
          contact: '9654321094',
          workingDays: 'Monday to Friday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2100',
          images: ['img45.jpg', 'img46.jpg'],
          terms_condition: 'Discounts available for weekly orders. No cancellations after 6 PM.'
        },
        {
          id: 4,
          name: 'Spicy Bites',
          streetAddress: '101 Banjara Hills',
          city: 'Hyderabad',
          state: 'Telangana',
          contact: '9988776656',
          workingDays: 'Monday to Sunday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2700',
          images: ['img47.jpg', 'img48.jpg'],
          terms_condition: 'Meals can be adjusted as per taste. 50% refund for cancellations 2 hours before delivery.'
        },
        {
          id: 5,
          name: 'Tiffin Express',
          streetAddress: '202 Jubilee Hills',
          city: 'Hyderabad',
          state: 'Telangana',
          contact: '9777888991',
          workingDays: 'Wednesday to Monday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2200',
          images: ['img49.jpg', 'img50.jpg'],
          terms_condition: 'No refunds for missed orders. Minimum order of 3 meals required.'
        }
      ],
      kolkata: [
        {
          id: 1,
          name: 'Kolkata Tiffin Service',
          streetAddress: '123 Howrah Bridge',
          city: 'Kolkata',
          state: 'West Bengal',
          contact: '9876543213',
          workingDays: 'Monday to Saturday',
          mealTimings: 'Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2400',
          images: ['img51.jpg', 'img52.jpg'],
          terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
        },
        {
          id: 2,
          name: 'Bengali Bites',
          streetAddress: '456 Victoria Memorial',
          city: 'Kolkata',
          state: 'West Bengal',
          contact: '9123456784',
          workingDays: 'Tuesday to Sunday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2200',
          images: ['img53.jpg', 'img54.jpg'],
          terms_condition: 'Orders can be customized. No refunds after meal delivery.'
        },
        {
          id: 3,
          name: 'Taste of Kolkata',
          streetAddress: '789 Park Street',
          city: 'Kolkata',
          state: 'West Bengal',
          contact: '9654321095',
          workingDays: 'Monday to Friday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2100',
          images: ['img55.jpg', 'img56.jpg'],
          terms_condition: 'Discounts available for weekly orders. No cancellations after 6 PM.'
        },
        {
          id: 4,
          name: 'Spice Junction',
          streetAddress: '101 Salt Lake',
          city: 'Kolkata',
          state: 'West Bengal',
          contact: '9988776657',
          workingDays: 'Monday to Sunday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Both (Veg & Non-Veg)',
          charges: '₹2300',
          images: ['img57.jpg', 'img58.jpg'],
          terms_condition: 'Meals can be adjusted as per taste. 50% refund for cancellations 2 hours before delivery.'
        },
        {
          id: 5,
          name: 'Flavours of Bengal',
          streetAddress: '202 Dum Dum',
          city: 'Kolkata',
          state: 'West Bengal',
          contact: '9777888992',
          workingDays: 'Wednesday to Monday',
          mealTimings: 'Breakfast, Lunch, Dinner',
          mealType: 'Veg',
          charges: '₹2000',
          images: ['img59.jpg', 'img60.jpg'],
          terms_condition: 'No refunds for missed orders. Minimum order of 3 meals required.'
        }
      ]
  };