export const cityData = {
  bangalore: [
    {
      id: 1,
      name: 'The Veggie Delight',
      profile_image: "/profile_images/image2.webp",
      ratings: "4.5",
      streetAddress: '123 Green Street',
      city: 'Bangalore',
      state: 'Karnataka',
      contact: '9876543210',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2000',
      images: ['/food/image1.jpg', '/food/image2.jpg', '/food/image3.jpg', '/food/image4.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 2,
      name: 'Spicy Bites',
      profile_image: "/profile_images/image1.webp",
      ratings: "4.0",
      streetAddress: '456 Spice Lane',
      city: 'Bangalore',
      state: 'Karnataka',
      contact: '9123456789',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2500',
      images: ['/food/image1.jpg', '/food/image2.jpg', '/food/image3.jpg', '/food/image4.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 3,
      name: 'Healthy Eats',
      profile_image: "/profile_images/image3.webp",
      ratings: "4.8",
      streetAddress: '789 Healthy Way',
      city: 'Bangalore',
      state: 'Karnataka',
      contact: '9988776655',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹1800',
      images: ['/food/image5.jpg', '/food/image6.jpg', '/food/image7.jpg', '/food/image8.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 4,
      name: 'HomeStyle Meals',
      profile_image: "/profile_images/image4.webp",
      ratings: "4.2",
      streetAddress: '321 Home Street',
      city: 'Bangalore',
      state: 'Karnataka',
      contact: '9765432100',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2300',
      images: ['/food/image9.jpg', '/food/image10.jpg', '/food/image11.jpg', '/food/image12.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    },
    {
      id: 5,
      name: 'Tasty Treats',
      profile_image: "/profile_images/image5.webp",
      ratings: "4.6",
      streetAddress: '654 Taste Blvd',
      city: 'Bangalore',
      state: 'Karnataka',
      contact: '9876501234',
      workingDays: 'Wednesday to Sunday',
      mealTimings: 'Breakfast, Lunch',
      mealType: 'Veg',
      charges: '₹2100',
      images: ['/food/image13.jpg', '/food/image14.jpg', '/food/image15.jpg', '/food/image16.jpg'],
      terms_condition: 'No cancellations within 24 hours. Payment in advance.'
    }
  ],
  delhi: [
    {
      id: 1,
      name: 'Capital Cuisines',
      profile_image: "/profile_images/image6.webp",
      ratings: "4.7",
      streetAddress: '111 Rajpath Marg',
      city: 'Delhi',
      state: 'Delhi',
      contact: '9123456780',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2700',
      images: ['/food/image17.jpg', '/food/image18.jpg', '/food/image19.jpg', '/food/image20.jpg'],
      terms_condition: 'Minimum order of 4 meals required. No refunds.'
    },
    {
      id: 2,
      name: 'Dilli Delight',
      profile_image: "/profile_images/image7.webp",
      ratings: "4.3",
      streetAddress: '222 Connaught Place',
      city: 'Delhi',
      state: 'Delhi',
      contact: '9988776650',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2200',
      images: ['/food/image21.jpg', '/food/image22.jpg', '/food/image23.jpg', '/food/image24.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 3,
      name: 'Taste of Delhi',
      profile_image: "/profile_images/image8.webp",
      ratings: "4.1",
      streetAddress: '333 Spice Market',
      city: 'Delhi',
      state: 'Delhi',
      contact: '9876501230',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2600',
      images: ['/food/image25.jpg', '/food/image26.jpg', '/food/image27.jpg', '/food/image28.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 4,
      name: 'Healthy Bites',
      profile_image: "/profile_images/image9.webp",
      ratings: "4.9",
      streetAddress: '444 Fitness St',
      city: 'Delhi',
      state: 'Delhi',
      contact: '9876543211',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹2000',
      images: ['/food/image29.jpg', '/food/image30.jpg', '/food/image31.jpg', '/food/image32.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 5,
      name: 'HomeFood Hub',
      profile_image: "/profile_images/image10.webp",
      ratings: "4.4",
      streetAddress: '555 Home Lane',
      city: 'Delhi',
      state: 'Delhi',
      contact: '9123456781',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2500',
      images: ['/food/image33.jpg', '/food/image34.jpg', '/food/image35.jpg', '/food/image36.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    }
  ],
  mumbai: [
    {
      id: 1,
      name: 'Mumbai Magic',
      profile_image: "/profile_images/image11.webp",
      ratings: "4.5",
      streetAddress: '111 Marine Drive',
      city: 'Mumbai',
      state: 'Maharashtra',
      contact: '9876543212',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2800',
      images: ['/food/image37.jpg', '/food/image38.jpg', '/food/image39.jpg', '/food/image40.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 2,
      name: 'Spice City',
      profile_image: "/profile_images/image12.webp",
      ratings: "4.0",
      streetAddress: '222 Bollywood Blvd',
      city: 'Mumbai',
      state: 'Maharashtra',
      contact: '9123456782',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2400',
      images: ['/food/image41.jpg', '/food/image42.jpg', '/food/image43.jpg', '/food/image44.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 3,
      name: 'Urban Eats',
      profile_image: "/profile_images/image13.webp",
      ratings: "4.7",
      streetAddress: '333 Skyline St',
      city: 'Mumbai',
      state: 'Maharashtra',
      contact: '9876501231',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹2100',
      images: ['/food/image45.jpg', '/food/image46.jpg', '/food/image47.jpg', '/food/image48.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 4,
      name: 'Healthy Meals',
      profile_image: "/profile_images/image14.webp",
      ratings: "4.2",
      streetAddress: '444 Wellness Way',
      city: 'Mumbai',
      state: 'Maharashtra',
      contact: '9988776651',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2600',
      images: ['/food/image49.jpg', '/food/image50.jpg', '/food/image51.jpg', '/food/image52.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    },
    {
      id: 5,
      name: 'Taste of Mumbai',
      profile_image: "/profile_images/image15.webp",
      ratings: "4.6",
      streetAddress: '555 Biryani Blvd',
      city: 'Mumbai',
      state: 'Maharashtra',
      contact: '9876543213',
      workingDays: 'Wednesday to Sunday',
      mealTimings: 'Breakfast, Lunch',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2300',
      images: ['/food/image53.jpg', '/food/image54.jpg', '/food/image55.jpg', '/food/image56.jpg'],
      terms_condition: 'No cancellations within 24 hours. Payment in advance.'
    }
  ],
  pune: [
    {
      id: 1,
      name: 'Pune Delights',
      profile_image: "/profile_images/image16.webp",
      ratings: "4.8",
      streetAddress: '111 Shivaji Road',
      city: 'Pune',
      state: 'Maharashtra',
      contact: '9876543214',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2200',
      images: ['/food/image57.jpg', '/food/image58.jpg', '/food/image59.jpg', '/food/image60.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 2,
      name: 'Spicy Flavours',
      profile_image: "/profile_images/image17.webp",
      ratings: "4.3",
      streetAddress: '222 Spice Street',
      city: 'Pune',
      state: 'Maharashtra',
      contact: '9123456783',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2600',
      images: ['/food/image61.jpg', '/food/image62.jpg', '/food/image63.jpg', '/food/image64.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 3,
      name: 'Healthwise Meals',
      profile_image: "/profile_images/image18.webp",
      ratings: "4.9",
      streetAddress: '333 Fitness Avenue',
      city: 'Pune',
      state: 'Maharashtra',
      contact: '9876501232',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹2000',
      images: ['/food/image65.jpg', '/food/image66.jpg', '/food/image67.jpg', '/food/image68.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 4,
      name: 'Homestyle Pune',
      profile_image: "/profile_images/image19.webp",
      ratings: "4.4",
      streetAddress: '444 Home St',
      city: 'Pune',
      state: 'Maharashtra',
      contact: '9876543215',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2500',
      images: ['/food/image69.jpg', '/food/image70.jpg', '/food/image71.jpg', '/food/image72.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    },
    {
      id: 5,
      name: 'Pune Flavours',
      profile_image: "/profile_images/image20.webp",
      ratings: "4.6",
      streetAddress: '555 Biryani Road',
      city: 'Pune',
      state: 'Maharashtra',
      contact: '9876543216',
      workingDays: 'Wednesday to Sunday',
      mealTimings: 'Breakfast, Lunch',
      mealType: 'Veg',
      charges: '₹2300',
      images: ['/food/image73.jpg', '/food/image74.jpg', '/food/image75.jpg', '/food/image76.jpg'],
      terms_condition: 'No cancellations within 24 hours. Payment in advance.'
    }
  ],
  hyderabad: [
    {
      id: 1,
      name: 'Hyderabadi Flavours',
      profile_image: "/profile_images/image21.webp",
      ratings: "4.5",
      streetAddress: '111 Charminar St',
      city: 'Hyderabad',
      state: 'Telangana',
      contact: '9876543217',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2500',
      images: ['/food/image77.jpg', '/food/image78.jpg', '/food/image79.jpg', '/food/image80.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 2,
      name: 'Spice Treats',
      profile_image: "/profile_images/image22.webp",
      ratings: "4.0",
      streetAddress: '222 Biryani Blvd',
      city: 'Hyderabad',
      state: 'Telangana',
      contact: '9123456784',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2400',
      images: ['/food/image81.jpg', '/food/image82.jpg', '/food/image83.jpg', '/food/image84.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 3,
      name: 'Healthy Hyderabadi',
      profile_image: "/profile_images/image23.webp",
      ratings: "4.7",
      streetAddress: '333 Fitness Lane',
      city: 'Hyderabad',
      state: 'Telangana',
      contact: '9876501233',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹2100',
      images: ['/food/image85.jpg', '/food/image86.jpg', '/food/image87.jpg', '/food/image88.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 4,
      name: 'Home Food Hub',
      profile_image: "/profile_images/image24.webp",
      ratings: "4.2",
      streetAddress: '444 Home Avenue',
      city: 'Hyderabad',
      state: 'Telangana',
      contact: '9988776652',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2600',
      images: ['/food/image89.jpg', '/food/image90.jpg', '/food/image91.jpg', '/food/image92.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    },
    {
      id: 5,
      name: 'Hyderabadi Delights',
      profile_image: "/profile_images/image25.webp",
      ratings: "4.6",
      streetAddress: '555 Taste St',
      city: 'Hyderabad',
      state: 'Telangana',
      contact: '9876543218',
      workingDays: 'Wednesday to Sunday',
      mealTimings: 'Breakfast, Lunch',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2300',
      images: ['/food/image93.jpg', '/food/image94.jpg', '/food/image95.jpg', '/food/image96.jpg'],
      terms_condition: 'No cancellations within 24 hours. Payment in advance.'
    }
  ],
  jaipur: [
    {
      id: 1,
      name: 'Royal Rajasthani',
      profile_image: "/profile_images/image26.webp",
      ratings: "4.9",
      streetAddress: '111 Pink City Road',
      city: 'Jaipur',
      state: 'Rajasthan',
      contact: '9876543219',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2400',
      images: ['/food/image97.jpg', '/food/image98.jpg', '/food/image99.jpg', '/food/image100.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 2,
      name: 'Spice Royals',
      profile_image: "/profile_images/image27.webp",
      ratings: "4.4",
      streetAddress: '222 Hawa Mahal St',
      city: 'Jaipur',
      state: 'Rajasthan',
      contact: '9123456785',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2600',
      images: ['/food/image101.jpg', '/food/image102.jpg', '/food/image103.jpg', '/food/image104.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 3,
      name: 'Healthy Jaipur',
      profile_image: "/profile_images/image28.webp",
      ratings: "4.8",
      streetAddress: '333 Fitness Street',
      city: 'Jaipur',
      state: 'Rajasthan',
      contact: '9876501234',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹2100',
      images: ['/food/image105.jpg', '/food/image106.jpg', '/food/image107.jpg', '/food/image108.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 4,
      name: 'Home Meals Jaipur',
      profile_image: "/profile_images/image29.webp",
      ratings: "4.3",
      streetAddress: '444 Home St',
      city: 'Jaipur',
      state: 'Rajasthan',
      contact: '9988776653',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2500',
      images: ['/food/image109.jpg', '/food/image110.jpg', '/food/image111.jpg', '/food/image112.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    },
    {
      id: 5,
      name: 'Jaipur Delights',
      profile_image: "/profile_images/image30.webp",
      ratings: "4.6",
      streetAddress: '555 Biryani Lane',
      city: 'Jaipur',
      state: 'Rajasthan',
      contact: '9876543220',
      workingDays: 'Wednesday to Sunday',
      mealTimings: 'Breakfast, Lunch',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2300',
      images: ['/food/image113.jpg', '/food/image114.jpg', '/food/image115.jpg', '/food/image116.jpg'],
      terms_condition: 'No cancellations within 24 hours. Payment in advance.'
    }
  ],
  kolkata: [
    {
      id: 1,
      name: 'Bengali Bites',
      profile_image: "/profile_images/image31.webp",
      ratings: "4.5",
      streetAddress: '111 Howrah Lane',
      city: 'Kolkata',
      state: 'West Bengal',
      contact: '9876543221',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Breakfast, Lunch, Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2500',
      images: ['/food/image117.jpg', '/food/image118.jpg', '/food/image119.jpg', '/food/image120.jpg'],
      terms_condition: 'No cancellations within 24 hours. Minimum order of 5 meals required.'
    },
    {
      id: 2,
      name: 'Spicy Bengali',
      profile_image: "/profile_images/image32.webp",
      ratings: "4.0",
      streetAddress: '222 Durga Road',
      city: 'Kolkata',
      state: 'West Bengal',
      contact: '9123456786',
      workingDays: 'Tuesday to Sunday',
      mealTimings: 'Lunch, Dinner',
      mealType: 'Veg',
      charges: '₹2400',
      images: ['/food/image121.jpg', '/food/image122.jpg', '/food/image123.jpg', '/food/image124.jpg'],
      terms_condition: 'Orders can be customized. No refunds after meal delivery.'
    },
    {
      id: 3,
      name: 'Healthy Kolkata',
      profile_image: "/profile_images/image33.webp",
      ratings: "4.7",
      streetAddress: '333 Fitness Blvd',
      city: 'Kolkata',
      state: 'West Bengal',
      contact: '9876501235',
      workingDays: 'Monday to Friday',
      mealTimings: 'Lunch',
      mealType: 'Veg',
      charges: '₹2100',
      images: ['/food/image125.jpg', '/food/image126.jpg', '/food/image127.jpg', '/food/image128.jpg'],
      terms_condition: 'No cancellations. Payment in advance.'
    },
    {
      id: 4,
      name: 'Home Taste Kolkata',
      profile_image: "/profile_images/image34.webp",
      ratings: "4.2",
      streetAddress: '444 Home St',
      city: 'Kolkata',
      state: 'West Bengal',
      contact: '9988776654',
      workingDays: 'Monday to Saturday',
      mealTimings: 'Dinner',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2600',
      images: ['/food/image129.jpg', '/food/image130.jpg', '/food/image131.jpg', '/food/image132.jpg'],
      terms_condition: 'Minimum order of 3 meals required. No refunds.'
    },
    {
      id: 5,
      name: 'Kolkata Delights',
      profile_image: "/profile_images/image35.webp",
      ratings: "4.6",
      streetAddress: '555 Rasgulla Road',
      city: 'Kolkata',
      state: 'West Bengal',
      contact: '9876543222',
      workingDays: 'Wednesday to Sunday',
      mealTimings: 'Breakfast, Lunch',
      mealType: 'Both (Veg & Non-Veg)',
      charges: '₹2300',
      images: ['/food/image133.jpg', '/food/image134.jpg', '/food/image135.jpg', '/food/image136.jpg'],
      terms_condition: 'No cancellations within 24 hours. Payment in advance.'
    }
  ]
}
